fun main() {
    val service = NoteService()
    val serviceComment = CommentService()
    val note1 = Note(1, 111, "note1", "text1", 11111111, deleted = true)
    val note2 = Note(1, 222, "note2", "text2", 22222222, deleted = true)
    val note3 = Note(1, 333, "note3", "text3", 33333333, deleted = true)
    val note4 = Note(1, 444, "note4", "text4", 44444444, deleted = true)
    val comment1 = Comment(1, 1, "comment 1", 1, true)
    val comment2 = Comment(2, 2, "comment 2", 2, true)
    val newNote = Note(5, 555, "newNote", "newNText", 55555555, deleted = true)
    val newComment = Comment(3, 3, "new comment", 3, true)

    service.add(note1)
    service.add(note2)
    service.add(note3)
    service.add(note4)
    serviceComment.add(comment1)
    serviceComment.add(comment2)
    service.delete(3)
    serviceComment.delete(1)
    service.getById(2)
    service.getById(1)
    serviceComment.getById(4)
    serviceComment.restore(1)
    service.edit(1, newNote)
    serviceComment.edit(1, newComment)
    serviceComment.delete(3)

}
